password_length: '6'
upper_case_length: '1'
lower_case_length: '0'
special_char_length: '1'
numeric_length: '1'
pass_reuse: '2'
exclude_admin: 1
force_validation: 1
validate_message: 'Please enter you details accordingly.'
en_pass_reuse: 0
_core:
  default_config_hash: MVlHF6Spb3vHq2cXlvNufiJJCyEA59M7M1AMCXoBkRU
